version: "3.8"

services:
  webapp:
    image: lombokhalalroom/lombok-halal-room-web-app:latest
    container_name: lhr-webapp-jenkins
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
